// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'rag/rag_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1112422266954378941),
    name: 'DocumentChunk',
    lastPropertyId: const obx_int.IdUid(6, 3717673101144106943),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4155754886312531779),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5987911420145767521),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5287688958406205515),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3339181545278501516),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 184306280175778289),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6805511288460611945),
        name: 'metadata',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3717673101144106943),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 1112422266954378941),
    lastIndexId: const obx_int.IdUid(1, 184306280175778289),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
      model: _entities[0],
      toOneRelations: (DocumentChunk object) => [],
      toManyRelations: (DocumentChunk object) => {},
      getId: (DocumentChunk object) => object.id,
      setId: (DocumentChunk object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunk object, fb.Builder fbb) {
        final sourceOffset = object.source == null
            ? null
            : fbb.writeString(object.source!);
        final contentOffset = object.content == null
            ? null
            : fbb.writeString(object.content!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final metadataOffset = object.metadata == null
            ? null
            : fbb.writeString(object.metadata!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sourceOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.addOffset(4, metadataOffset);
        fbb.addInt64(5, object.createdAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final metadataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final object = DocumentChunk(
          source: sourceParam,
          content: contentParam,
          embedding: embeddingParam,
          metadata: metadataParam,
          createdAt: createdAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[0],
  );

  /// See [DocumentChunk.source].
  static final source = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[1],
  );

  /// See [DocumentChunk.content].
  static final content = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[2],
  );

  /// See [DocumentChunk.embedding].
  static final embedding = obx.QueryHnswProperty<DocumentChunk>(
    _entities[0].properties[3],
  );

  /// See [DocumentChunk.metadata].
  static final metadata = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[4],
  );

  /// See [DocumentChunk.createdAt].
  static final createdAt = obx.QueryDateProperty<DocumentChunk>(
    _entities[0].properties[5],
  );
}
